export const LEVELS = ['never', 'sometimes', 'often', 'always'];
export const MILKS = ['cow', 'soy', 'oat'];
export const BREAKFASTS = ['british', 'continental', 'milk', 'vegan'];
export const TRASH_LEVELS = ['base', 'reduction', 'zero'];
export const CAR_TYPES = ['small', 'medium', 'berline', 'vul', 'suv'];
export const CAR_MOTORS = ['thermic', 'hybrid', 'electric'];
export const CAR_FUELS = ['essence', 'bio', 'gazole', 'gpl'];
export const MOTO_TYPES = ['thermic', 'electric', 'inf250', 'sup250'];
export const WOOD_TYPES = ['log', 'pellets'];