export * from './clothes';
export * from './consomable';
export * from './furnitures';
export * from './hobbies';
export * from './home-appliances';
export * from './newManufact';
export * from './pets';
export * from './smoking';
export * from './tech';